name:                dvm
version:             0.1.0.0
github:              "githubuser/dvm"
license:             BSD3
author:              "Joe Thornber"
maintainer:          "ejt@redhat.com"
copyright:           "2019 RedHat Ltd"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/dvm#readme>

dependencies:
- aeson
- aeson-pretty
- array
- async
- attoparsec
- base >= 4.7 && < 5
- binary
- bytestring
- containers
- fgl
- lens
- mtl
- prettyprinter
- protolude
- stm
- text
- typed-process
- unix
- unordered-containers

library:
  source-dirs: src
  ghc-options:
    - -XNoImplicitPrelude
    - -XOverloadedStrings

executables:
  dvm:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -XNoImplicitPrelude
    - -XOverloadedStrings
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dvm

tests:
  dvm-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -XNoImplicitPrelude
    - -XOverloadedStrings
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dvm
    - hspec
    - QuickCheck

