name:                dvm
version:             0.1.0.0
github:              "githubuser/dvm"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2019 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/dvm#readme>

dependencies:
- aeson >= 1.4.2.0
- async >= 2.1.1.1
- base >= 4.7 && < 5
- binary >= 0.8.6.0
- bytestring >= 0.10.8.2
- prettyprinter >= 1.2.1
- stm >= 2.5.0.0
- text >= 1.2.3.1
- typed-process >= 0.2.3.0
- unix >= 2.7.2.2

library:
  source-dirs: src

executables:
  dvm:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dvm

tests:
  dvm-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dvm
